version: '3'

services:
  demo:
    image: 'ngquangdat/demo:latest'
    container_name: 'demo'
    depends_on:
      - redis
    ports:
      - '8081:8081'
    networks:
      - demo_network
    volumes:
      - ./config:/opt/ngquangdat/demo/config
    environment:
      JAVA_OPTS: '-Dspring.config.additional-location=/opt/ngquangdat/demo/config/'
  redis:
    image: 'redis/redis-stack:latest'
    container_name: 'redis'
    ports:
      - '6379:6379'
      - '8001:8001'
    environment:
      - REDIS_ARGS=--requirepass mypassword
    networks:
      - demo_network
networks:
  demo_network:
    driver: bridge