
INSERT INTO api_sync_config (api_url, target_table, record_json_path, page_response_path, total_page_response_path, total_count_response_path, last_synced, sync_code, status, http_method, clean_condition, upsert_key, parallel) VALUES('https://api.hsx.vn/mk/api/v1/market/trading-report', 'trading_report', '$.data', NULL, NULL, NULL, NULL, 'TRADING_REPORT', NULL, 'GET', NULL, NULL, NULL);
INSERT INTO api_sync_config (api_url, target_table, record_json_path, page_response_path, total_page_response_path, total_count_response_path, last_synced, sync_code, status, http_method, clean_condition, upsert_key, parallel) VALUES('https://api.hsx.vn/mk/api/v1/market/trading-report-odd', 'trading_report_odd', '$.data', NULL, NULL, NULL, NULL, 'TRADING_REPORT_ODD', NULL, 'GET', NULL, NULL, NULL);

INSERT INTO api_sync_param_config (config_id, param_name, param_type, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT'), 'startDate', NULL, NULL, '#LOCAL_DATE_YYYY_MM_DD_PRE_1');
INSERT INTO api_sync_param_config (config_id, param_name, param_type, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT'), 'endDate', NULL, NULL, '#LOCAL_DATE_YYYY_MM_DD');
INSERT INTO api_sync_param_config (config_id, param_name, param_type, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT_ODD'), 'startDate', NULL, NULL, '#LOCAL_DATE_YYYY_MM_DD_PRE_1');
INSERT INTO api_sync_param_config (config_id, param_name, param_type, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT_ODD'), 'endDate', NULL, NULL, '#LOCAL_DATE_YYYY_MM_DD');

INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT'), 'mainVolume', 'main_volume', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT'), 'mainValue', 'main_value', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT'), 'bigLotVolume', 'big_lot_volume', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT'), 'bigLotValue', 'big_lot_value', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT'), 'buyingVolume', 'buying_volume', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT'), 'buyingOrder', 'buying_order', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT'), 'sellingVolume', 'selling_volume', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT'), 'sellingOrder', 'selling_order', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT'), 'totalVolume', 'total_volume', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT'), 'totalValue', 'total_value', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT'), NULL, 'record_date', NULL, '#LOCAL_DATE_TIME');

INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT_ODD'), 'mainVolume', 'main_volume', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT_ODD'), 'mainValue', 'main_value', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT_ODD'), 'bigLotVolume', 'big_lot_volume', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT_ODD'), 'bigLotValue', 'big_lot_value', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT_ODD'), 'buyingVolume', 'buying_volume', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT_ODD'), 'buyingOrder', 'buying_order', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT_ODD'), 'sellingVolume', 'selling_volume', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT_ODD'), 'sellingOrder', 'selling_order', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT_ODD'), 'totalVolume', 'total_volume', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT_ODD'), 'totalValue', 'total_value', NULL, NULL);
INSERT INTO api_sync_field_mapping (config_id, json_path, target_column, default_value, operation) VALUES((select id from api_sync_config  where sync_code ='TRADING_REPORT_ODD'), NULL, 'record_date', NULL, '#LOCAL_DATE_TIME');
